// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkNzakK62GZc3FpefXqR8TkAGDkgjCpdA',
    appId: '1:305490436655:web:c67b05c42634aef5d99cda',
    messagingSenderId: '305490436655',
    projectId: 'quizapk-f55cb',
    authDomain: 'quizapk-f55cb.firebaseapp.com',
    storageBucket: 'quizapk-f55cb.appspot.com',
    measurementId: 'G-4NBKQBR6DC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByxhO5wHRv8gMkRI8oVnmBfz_jx1lQgkk',
    appId: '1:305490436655:android:e3e63d913ffe907dd99cda',
    messagingSenderId: '305490436655',
    projectId: 'quizapk-f55cb',
    storageBucket: 'quizapk-f55cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDUNb8yGkr3Ljj4DpbEaz1qB5shE4RVvI',
    appId: '1:305490436655:ios:788756db7247355ad99cda',
    messagingSenderId: '305490436655',
    projectId: 'quizapk-f55cb',
    storageBucket: 'quizapk-f55cb.appspot.com',
    iosBundleId: 'com.example.quizMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDUNb8yGkr3Ljj4DpbEaz1qB5shE4RVvI',
    appId: '1:305490436655:ios:788756db7247355ad99cda',
    messagingSenderId: '305490436655',
    projectId: 'quizapk-f55cb',
    storageBucket: 'quizapk-f55cb.appspot.com',
    iosBundleId: 'com.example.quizMaster',
  );
}
